#
# Copyright (C) 2008-2019 Jerrykuku
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Hyper Theme
LUCI_DEPENDS:=+curl +jsonfilter
PKG_VERSION:=1.1
PKG_RELEASE:=20220505

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
