#!/bin/sh

if [ "$(uci -q get luci.themes.HyperG)" = "" ]; then
	uci batch <<-EOF
		set luci.themes.HyperG=/luci-static/hyperg
		set luci.main.mediaurlbase=/luci-static/hyperg
		commit luci
	EOF
fi
exit 0
